version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mytapp
    ports:
      - '5432:5432'
  backend:
    build: ./back
    ports:
      - "3001:3001"
    depends_on:
      - db